### ISSUE TITLE
Botler takes too mush time to load NLP

### ISSUE THREAD

**Issue by SamiAyed** [fyndme/bot-framework#1]
I noticed that my node server was slow to start ( 2 - 5 minutes ). So i did some debuging and it appears that `const bot = new Botler([`${__dirname}/nlp`]);` takes a lot of time to load ( i have 13 foldes and more than 30 files ).
I thought we could make this better by dumping the loaded data to redis and load it the next time the bot loads.

**Comment by adamjuhasz** [comment]
The current code in the repo caches the classifiers into json files that it just reloads, I wanted to think through the implementation and run some tests before I officially pushed it to NPM. If you're willing to test out the code by setting your package.json to point to the github repo that would be awesome feedback.

**Comment by adamjuhasz** [comment]
Also, would you mind sharing some of the new phrases, I would love to grow all the built in phrases that botler has!

**Comment by SamiAyed** [comment]
Sorry for the late feedback, i tried it, it is very fast to load in fact but i had some issues. The bot didn't enter in the correct intent and had some unusual comportment, so continued working with the older version.
For the phrases, they are in french, i will try to make an English version and will share it with you :D
Thnx for the fast response and sorry for the late feedback.

**Comment by adamjuhasz** [comment]
I think the new version has some improvements that will help you out. I think the new english intents were confusing your french ones. The new version won't pull in the default english intents if you provide your own directory. Try it out, should give you speed + correctness
